force-app/main/default/objects/Demo_Org_Wizard_Page_1__mdt/Demo_Org_Wizard_Page_1__mdt.object-meta.xml
<CustomObject>
    <label>Demo Org Wizard - Step 1 Field</label>
    <pluralLabel>Demo Org Wizard - Step 1 fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Demo_Org_Wizard_Page_1__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>The API Name of the Demo Org custom object field you would like to display in the New Demo Org Wizard - Page 1</description>
    <inlineHelpText>The API Name of the Demo Org custom object field you would like to display in the New Demo Org Wizard - Page 1</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Demo_Org_Wizard_Page_1__mdt/fields/Field_Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Field_Display_Order__c</fullName>
    <description>The order that this Demo Org custom object field show be displayed in the Demo Org Wizard - Page 1</description>
    <inlineHelpText>The order that this field show be displayed in the Demo Org Wizard - Page 1</inlineHelpText>
    <label>Field Display Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Demo_Org_Wizard_Page_1__mdt/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <description>The api type of the field. Select from one of the options.</description>
    <inlineHelpText>The api type of the field. Select from one of the options.</inlineHelpText>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
                <default>true</default>
                <label>text</label>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>time</fullName>
            </value>
            <value>
                <fullName>tel</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>toggle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewDemoOrgWizardApexController.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */


public with sharing class NewDemoOrgWizardApexController {
    @AuraEnabled(cacheable=true)
    public static List<Demo_Org_Wizard_Page_1__mdt> getStep1Fields() {

        List<Demo_Org_Wizard_Page_1__mdt> lstOfFields = [SELECT Label, Field_API_Name__c, Field_Type__c FROM Demo_Org_Wizard_Page_1__mdt WITH SECURITY_ENFORCED order by Field_Display_Order__c asc];
        System.debug('######## lstOfFields: ' + lstOfFields);
        return lstOfFields;
    }
}