force-app/main/default/objects/Demo_Org__c/Demo_Org__c.object-meta.xml
<CustomObject>
    <label>Demo Org</label>
    <nameField>
        <label>Demo Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Org__c/fields/Signup_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Signup_Request_Id__c</fullName>
    <externalId>true</externalId>
    <label>Signup Request Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Org__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;In Progress&quot;</defaultValue>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/schedFetchOrgStatus.cls
public with sharing class schedFetchOrgStatus implements Schedulable, Database.AllowsCallouts {

    public String signupReqId { get;set; }
    public String localDemoOrgRecId { get;set; }

    public void execute(SchedulableContext SC) {
        Map<String, String> demoOrginProgressMap = new Map<String, String>();
        List<Demo_Org__c> lstLocalRecsPending = [SELECT Id,Signup_Request_Id__c FROM Demo_Org__c where Status__c = 'In Progress' OR Status__c = 'InProgress'];
        System.debug('#### lstLocalRecsPending: ' + lstLocalRecsPending);
        if (lstLocalRecsPending.size() > 0)
        {
            for (Demo_Org__c d : lstLocalRecsPending)
            {
                demoOrginProgressMap.put(d.Signup_Request_Id__c, d.Id);
            }
            System.debug('#### demoOrginProgressMap: ' + demoOrginProgressMap);
            //callSignupAPI.updateLocalDemoOrgStatus(demoOrginProgressMap);
        }
        
     }

     
}