force-app/main/default/objects/Demo_Org__c/Demo_Org__c.object-meta.xml
<CustomObject>
    <label>Demo Org</label>
    <nameField>
        <label>Demo Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Org__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;In Progress&quot;</defaultValue>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SignupStatus__e/SignupStatus__e.object-meta.xml
<CustomObject>
    <label>SignupStatus</label>
    <pluralLabel>SignupStatus</pluralLabel>
</CustomObject>

force-app/main/default/objects/SignupStatus__e/fields/OrgId__c.field-meta.xml
<CustomField>
    <fullName>OrgId__c</fullName>
    <label>OrgId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SignupStatus__e/fields/OrgInstance__c.field-meta.xml
<CustomField>
    <fullName>OrgInstance__c</fullName>
    <label>OrgInstance</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SignupStatus__e/fields/OrgStatus__c.field-meta.xml
<CustomField>
    <fullName>OrgStatus__c</fullName>
    <label>OrgStatus</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/callSignupAPI.cls
public with sharing class callSignupAPI {

    @AuraEnabled
    public String status { get;set; }
    @AuraEnabled
    public String orgId { get;set; }
    
    @AuraEnabled(cacheable=false)
    public static callSignupAPI getRealTimeOrgStatus(String signupRecordId, String localDemoOrgRec)
    { 
        callSignupAPI rec = new callSignupAPI();
        SignupResponse s = getSignupResponse(signupRecordId, localDemoOrgRec, false);
        rec.orgId = s.CreatedOrgId;
        rec.status = s.Status;

        return rec;
    }

    private static SignupResponse getSignupResponse(String signupRecordId, String localDemoOrgRec, Boolean calledFromApexJob)
    {
        SignupResponse resp = new SignupResponse();
        
        String strFetchResult;

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:Signup_API_Org/services/data/v42.0/sobjects/SignupRequest/' + signupRecordId + '?fields=Status,CreatedOrgId,CreatedOrgInstance,ErrorCode,Username');
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');

        HttpResponse response = http.send(request);
        // Parse the JSON response

        System.debug('#### GET response: ' + response.getBody());
        strFetchResult = response.getBody();

        if (String.isNotEmpty(strFetchResult))
        {
            resp = SignupResponse.parse(strFetchResult);
            String strStatus = resp.Status;
            System.debug('#### SignupRequest Status: ' + strStatus);

            if (strStatus.equalsIgnoreCase('Success'))
            {
                // update the local demo org record status
                Demo_Org__c d = new Demo_Org__c(Id = localDemoOrgRec);
                d.Status__c = strStatus;
                update d;

                if (calledFromApexJob)
                {
                    // Fire Platform Event to notify LWCs that are waiting for ststus change
                    SignupStatus__e ev = new SignupStatus__e (OrgStatus__c = resp.Status, OrgId__c = resp.CreatedOrgId, OrgInstance__c = resp.CreatedOrgInstance);
                    Database.SaveResult sr = EventBus.publish(ev);
                    System.debug('#### Event Publish Status: ' + sr.isSuccess());
                    String jobName = 'schedFetchSignupStatus-' + localDemoOrgRec + '%';
                }
            }
        }
        return resp;
    }


    @future(callout=true)
    public static void getOrgStatus(String signupRecordId, String localDemoOrgRec)
    { 
        SignupResponse s = getSignupResponse(signupRecordId, localDemoOrgRec, true);
    }

    



}