force-app/main/default/objects/Demo_Feature__c/Demo_Feature__c.object-meta.xml
<CustomObject>
    <description>Features selected for the demo</description>
    <label>Demo Feature</label>
    <nameField>
        <label>Demo Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Feature__c/fields/Demo_Org__c.field-meta.xml
<CustomField>
    <fullName>Demo_Org__c</fullName>
    <label>Demo Org</label>
    <referenceTo>Demo_Org__c</referenceTo>
    <relationshipLabel>Demo Features</relationshipLabel>
    <relationshipName>Demo_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demo_Feature__c/fields/Demo_Product__c.field-meta.xml
<CustomField>
    <fullName>Demo_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demo Product</label>
    <referenceTo>Demo_Product__c</referenceTo>
    <relationshipLabel>Demo Features</relationshipLabel>
    <relationshipName>Demo_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demo_Feature__c/fields/Instruction_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Line_1__c</fullName>
    <label>Instruction Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Feature__c/fields/Instruction_Line_1_Completed__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Line_1_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Instruction Line 1 Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Feature__c/fields/Instruction_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Line_2__c</fullName>
    <label>Instruction Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Feature__c/fields/Instruction_Line_2_Completed__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Line_2_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Instruction Line 2 Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Feature__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Configured</fullName>
                <default>true</default>
                <label>Not Configured</label>
            </value>
            <value>
                <fullName>Configured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Org__c/Demo_Org__c.object-meta.xml
<CustomObject>
    <label>Demo Org</label>
    <nameField>
        <label>Demo Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Org__c/fields/Demo_Template__c.field-meta.xml
<CustomField>
    <fullName>Demo_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demo Template</label>
    <referenceTo>Demo_Template__c</referenceTo>
    <relationshipLabel>Demo Orgs</relationshipLabel>
    <relationshipName>Demo_Orgs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demo_Org__c/fields/Signup_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Signup_Request_Id__c</fullName>
    <externalId>true</externalId>
    <label>Signup Request Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Org__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;In Progress&quot;</defaultValue>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Org__c/fields/Trial_Days__c.field-meta.xml
<CustomField>
    <fullName>Trial_Days__c</fullName>
    <label>Trial Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demo_Org__c/fields/Type_of_App__c.field-meta.xml
<CustomField>
    <fullName>Type_of_App__c</fullName>
    <label>Type of App</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Product__c/Demo_Product__c.object-meta.xml
<CustomObject>
    <description>The Products included in the Demo (Trialforce Template)</description>
    <label>Demo Product</label>
    <nameField>
        <label>Demo Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Product__c/fields/Demo_Template__c.field-meta.xml
<CustomField>
    <fullName>Demo_Template__c</fullName>
    <label>Demo Template</label>
    <referenceTo>Demo_Template__c</referenceTo>
    <relationshipLabel>Demo Products</relationshipLabel>
    <relationshipName>Demo_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demo_Product__c/fields/Instruction_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Line_1__c</fullName>
    <label>Instruction Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Product__c/fields/Instruction_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Line_2__c</fullName>
    <label>Instruction Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Product__c/fields/Instructions_Doc__c.field-meta.xml
<CustomField>
    <fullName>Instructions_Doc__c</fullName>
    <label>Instructions Doc</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Product__c/fields/ISV_Instructions__c.field-meta.xml
<CustomField>
    <fullName>ISV_Instructions__c</fullName>
    <label>ISV Instructions</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Feature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Product__c/fields/Video_Id__c.field-meta.xml
<CustomField>
    <fullName>Video_Id__c</fullName>
    <label>Video Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Template__c/Demo_Template__c.object-meta.xml
<CustomObject>
    <label>Demo Template</label>
    <nameField>
        <label>Demo Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Template__c/fields/Main_Product__c.field-meta.xml
<CustomField>
    <fullName>Main_Product__c</fullName>
    <label>Main Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales and Service Cloud</fullName>
            </value>
            <value>
                <fullName>Financial Services Cloud</fullName>
            </value>
            <value>
                <fullName>Health Cloud</fullName>
            </value>
            <value>
                <fullName>Manufacturing Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Template__c/fields/Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Template_ID__c</fullName>
    <description>The Trialforce Template ID for the Demo</description>
    <inlineHelpText>Enter the Trialforce Template ID for the Demo</inlineHelpText>
    <label>Template ID</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestFactory.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */


@isTest
public without sharing class TestFactory {
    // define default constants that can be accessible to assert against.

    public static final String DEFAULT_MAIN_PRODUCT = 'Sales and Service Cloud';
    public static final String DEFAULT_NAME = 'Regular SDO';
    public static final String DEFAULT_TEMPLATE_ID = '0TT4S000000WXzv';

    public static final String DEFAULT_FEATURE_NAME = 'Next Best Action';
    public static final String DEFAULT_CATEGORY = 'Sales and Service Cloud';
    public static final String DEFAULT_INSTRUCTIONS_DOC = 'Regular SDO';
    public static final String DEFAULT_INSTRUCTION_LINE_1 = 'NBA Component shows user Recommendations (what to do next) based on Strategies (triggers)';
    public static final String DEFAULT_INSTRUCTION_LINE_2 = 'To set up NBA for your demo go to your object record and just Edit the Record Page and Drag and Drop the Einstein Next Best Action Lightning Component to your object record page';
    public static final String DEFAULT_ISV_INSTRUCTIONS = 'https://confluence.internal.salesforce.com/pages/viewpage.action?pageId=217029385';
    public static final String DEFAULT_VIDEO_ID = 'CVDi6PivA4RLVRtjJMCdwL';



    /* The “create” methods are used to instantiate the sobjects without inserting them. 
       This is tremendously helpful when you need to create a particular record and then tweak it before 
       it’s inserted from the calling code. */  
 

    /* The create methods are commonly overloaded to allow different properties to be set. */

    public static Demo_Template__c createDemoTemplate(){

           return new Demo_Template__c(
               Main_Product__c = DEFAULT_MAIN_PRODUCT,
               Name = DEFAULT_NAME,
               Template_ID__c = DEFAULT_TEMPLATE_ID
           );

    }


    public static Demo_Product__c createDemoProduct(String demoTemplateID){

           return new Demo_Product__c(
                Demo_Template__c = demoTemplateID,
                Instructions_Doc__c = DEFAULT_INSTRUCTIONS_DOC,
                Instruction_Line_1__c = DEFAULT_INSTRUCTION_LINE_1,
                Instruction_Line_2__c = DEFAULT_INSTRUCTION_LINE_2,
                ISV_Instructions__c = DEFAULT_ISV_INSTRUCTIONS,
                Name = DEFAULT_FEATURE_NAME,
                Status__c = 'Active',
                Type__c = 'Feature',
                Video_Id__c = DEFAULT_VIDEO_ID
           );

    }

    public static Demo_Org__c createLocalDemoOrgRec(String demoTemplateID){

        return new Demo_Org__c(
             Type_of_App__c = DEFAULT_CATEGORY,
             Trial_Days__c = 2.0,
             Demo_Template__c = demoTemplateID,
             Partner_Name__c = 'Partner A',
             Signup_Request_Id__c = '0SR5b000000TPAdGAO',
             Status__c = 'In Progress',
             Name = 'partner A - 5/7/2021'
        );

 }

 public static Demo_Feature__c createLocalDemoFeatureRec(String demoOrgRecId, String demoProductRecId, String demoProductName){

    return new Demo_Feature__c(
         Demo_Product__c = demoProductRecId,
         Demo_Org__c = demoOrgRecId,
         Instruction_Line_1_Completed__c = false,
         Instruction_Line_2_Completed__c = false,
         Name = demoProductName,
         Status__c = 'Not Configured'
    );

}
    
    


    /* The “Insert” methods are used to create the sobjects and then insert them. They delegate 
       the creation to the create methods and then insert the records. Like the create methods,
       the insert methods are overloaded to allow different properties to be set as necessary.
       Another best practice is to bulk insert or bulk create data, but to keep the sample short, that’s omitted. */

    public static Demo_Template__c insertDemoTemplate(){

          Demo_Template__c recToInsert = createDemoTemplate();
          insert recToInsert;
          return recToInsert;

    }

    public static Demo_Product__c insertDemoProduct(String demoTemplateId, string featureName){

          Demo_Product__c recToInsert = createDemoProduct(demoTemplateID);
          insert recToInsert;
          return recToInsert;

    }
    
    public static Demo_Org__c insertlocalDemoOrgRec(String demoTemplateID){

        Demo_Org__c recToInsert = createLocalDemoOrgRec(demoTemplateID);
        insert recToInsert;
        return recToInsert;

  }

  public static Demo_Feature__c insertlocalDemoFeatureRec(String demoOrgRecId, String demoProductRecId, String demoProductName){

    Demo_Feature__c recToInsert = createLocalDemoFeatureRec(demoOrgRecId, demoProductRecId, demoProductName);
    insert recToInsert;
    return recToInsert;

}
    

    public static String getUUID()
    {
            Blob b = Crypto.GenerateAESKey(128);
            String h = EncodingUtil.ConvertTohex(b);
            String guid = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
            system.debug(guid);
            return guid;
    }

}