force-app/main/default/objects/Demo_Feature__c/Demo_Feature__c.object-meta.xml
<CustomObject>
    <description>Features selected for the demo</description>
    <label>Demo Feature</label>
    <nameField>
        <label>Demo Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Feature__c/fields/Demo_Org__c.field-meta.xml
<CustomField>
    <fullName>Demo_Org__c</fullName>
    <label>Demo Org</label>
    <referenceTo>Demo_Org__c</referenceTo>
    <relationshipLabel>Demo Features</relationshipLabel>
    <relationshipName>Demo_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demo_Feature__c/fields/Demo_Product__c.field-meta.xml
<CustomField>
    <fullName>Demo_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demo Product</label>
    <referenceTo>Demo_Product__c</referenceTo>
    <relationshipLabel>Demo Features</relationshipLabel>
    <relationshipName>Demo_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demo_Org__c/Demo_Org__c.object-meta.xml
<CustomObject>
    <label>Demo Org</label>
    <nameField>
        <label>Demo Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Org__c/fields/Demo_Template__c.field-meta.xml
<CustomField>
    <fullName>Demo_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demo Template</label>
    <referenceTo>Demo_Template__c</referenceTo>
    <relationshipLabel>Demo Orgs</relationshipLabel>
    <relationshipName>Demo_Orgs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demo_Org__c/fields/Signup_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Signup_Request_Id__c</fullName>
    <externalId>true</externalId>
    <label>Signup Request Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Org_Wizard_Page_1__mdt/Demo_Org_Wizard_Page_1__mdt.object-meta.xml
<CustomObject>
    <label>Demo Org Wizard - Step 1 Field</label>
    <pluralLabel>Demo Org Wizard - Step 1 fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Demo_Product__c/Demo_Product__c.object-meta.xml
<CustomObject>
    <description>The Products included in the Demo (Trialforce Template)</description>
    <label>Demo Product</label>
    <nameField>
        <label>Demo Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Product__c/fields/Demo_Template__c.field-meta.xml
<CustomField>
    <fullName>Demo_Template__c</fullName>
    <label>Demo Template</label>
    <referenceTo>Demo_Template__c</referenceTo>
    <relationshipLabel>Demo Products</relationshipLabel>
    <relationshipName>Demo_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demo_Template__c/Demo_Template__c.object-meta.xml
<CustomObject>
    <label>Demo Template</label>
    <nameField>
        <label>Demo Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Template__c/fields/Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Template_ID__c</fullName>
    <description>The Trialforce Template ID for the Demo</description>
    <inlineHelpText>Enter the Trialforce Template ID for the Demo</inlineHelpText>
    <label>Template ID</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Slack_Settings__mdt/Slack_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Slack Setting</label>
    <pluralLabel>Slack Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/test_Trial_Launcher_Apex.cls
@isTest
private class test_Trial_Launcher_Apex {
    @testSetup static void setup() {
        // Create common test records

        Demo_Template__c dt = TestFactory.insertDemoTemplate();
        Demo_Product__c dp1 = TestFactory.insertDemoProduct(dt.Id, 'Next Best Action');
        Demo_Product__c dp2 = TestFactory.insertDemoProduct(dt.Id, 'Salesforce Maps');
        Demo_Org__c dr = TestFactory.insertlocalDemoOrgRec(dt.Id);
        Demo_Feature__c df1 = TestFactory.insertlocalDemoFeatureRec(dr.Id, dp1.Id, dp1.Name);
        Demo_Feature__c df2 = TestFactory.insertlocalDemoFeatureRec(dr.Id, dp2.Id, dp2.Name);
    }

    @isTest static void test_NewDemoOrgWizardApexController_CreateDemoOrg() {
        // Set mock callout class 
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new WebServiceMockImpl());
        Demo_Template__c dt = [SELECT Id, Template_ID__c FROM Demo_Template__c LIMIT 1];
        List<String> lstFeatures = new List<String>();
        lstFeatures.add('Next Best Action');
        lstFeatures.add('Salesforce Maps');
        NewDemoOrgWizardApexController lstRecs1 = NewDemoOrgWizardApexController.createDemoOrg('firstName', 'lastName', 'r@r.com', 'US', dt.Template_ID__c, 'partnerName', '2', '2021-05-07T07:30:00.000Z', lstFeatures, 'EN');
        Test.stopTest();
    }

    @isTest static void test_NewDemoOrgWizardApexController_GetSlackFields() {
        
        Test.startTest();
        List<Slack_Settings__mdt> lstRecs1 = NewDemoOrgWizardApexController.getSlackSettings();
        Test.stopTest();
    }

    @isTest static void test_NewDemoOrgWizardApexController_GetStep1Fields() {
        
        Test.startTest();
        List<Demo_Org_Wizard_Page_1__mdt> lstRecs1 = NewDemoOrgWizardApexController.getStep1Fields();
        Test.stopTest();
    }

    @isTest static void test_NewDemoOrgWizardApexController_GetFeaturesSelected() {
        
        Test.startTest();
        List<Demo_Feature__c> lstProds = [SELECT Id FROM Demo_Feature__c LIMIT 2];
        List<String> lStrings = new List<String>();
        for (Demo_Feature__c p: lstProds)
        {
            lStrings.add(p.id);
        }
        List<NewDemoOrgWizardApexController> lstRecs1 = NewDemoOrgWizardApexController.getFeaturesSelected(lStrings);
        Test.stopTest();
    }

    @isTest static void test_NewDemoOrgWizardApexController_GetMainProducts() {
        
        Test.startTest();
        List<NewDemoOrgWizardApexController> lstRecs1 = NewDemoOrgWizardApexController.getMainProducts();
        Test.stopTest();
    }

    @isTest static void test_NewDemoOrgWizardApexController_GetActiveFeatures() {
        
        Test.startTest();
        AggregateResult[] lstRecs1 = NewDemoOrgWizardApexController.getActiveFeatures();
        Test.stopTest();
    }

    @isTest static void test_NewDemoOrgWizardApexController_GetOrgURL() {
        
        Test.startTest();
        String lstRecs1 = NewDemoOrgWizardApexController.getOrgURL();
        Test.stopTest();
    }


    @isTest static void test_callSignupAPI_GetRealTimeOrgStatus() {
        // Set mock callout class 
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new WebServiceGetStatusMockImpl());
        Demo_Org__c drec = [SELECT Id,Signup_Request_Id__c FROM Demo_Org__c LIMIT 1];
        callSignupAPI lstRecs1 = callSignupAPI.getRealTimeOrgStatus(drec.Signup_Request_Id__c, drec.Id);
        Test.stopTest();
    }

    /*
    @isTest static void test_callSignupAPI_UpdateLocalDemoOrgStatus() {
        // Set mock callout class 
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new WebServiceGetStatusMockImpl());
        Demo_Org__c drec = [SELECT Id,Signup_Request_Id__c FROM Demo_Org__c LIMIT 1];
        Map<String, String> signupRecordIdsLocalRecsMap = new Map<String, String>();
        signupRecordIdsLocalRecsMap.put(drec.Signup_Request_Id__c, drec.Id);
        callSignupAPI.updateLocalDemoOrgStatus(signupRecordIdsLocalRecsMap);
        Test.stopTest();
    }
    */

    @isTest static void test_callSignupAPI_GetOrgStatus() {
        // Set mock callout class 
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new WebServiceGetStatusMockImpl());
        Demo_Org__c drec = [SELECT Id,Signup_Request_Id__c FROM Demo_Org__c LIMIT 1];
        callSignupAPI.getOrgStatus(drec.Signup_Request_Id__c, drec.Id);
        Test.stopTest();
    }

    @isTest
    static void testInstallScript() {
        postInstallScript postinstall = new postInstallScript();
        Test.testInstall(postinstall, null);
        Test.testInstall(postinstall, new Version(1,0), true);
        
    }

}